receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      filesystem:
      network:
      processes:

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000

exporters:
  debug:
    verbosity: basic
  otlphttp:
    endpoint: https://otel.kloudmate.dev:4318
    headers:
      Authorization: sk_6HY8YvsKOJouJNDTxK4kRQDE
  # prometheus:
  #   endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [debug, otlphttp]